# Constants {#constants-properties}

Properties for the `"constants"` node:

- `"constants"`: contains an array of key and value pairs, which are referenced by other items in the project. \
  Items reference key/value pairs via text labels using a special syntax. For example, `Wisteria::GraphItems::Label` objects or graph
  titles can embed a reference to a run-time value, which will be expanded when the report is rendered.
  - `"name"`: The key used for the item. Other items reference this using the syntax `{{name}}`, where *name* is the look-up key.
  - `"value"` either a string or numeric value to associate with the key. \
    If a number, then it will be formatted to the current locale when displayed in the report. \

Note that datasets have a similar `"formulas"` section which can create constants from self-referencing formulas.

::: {.minipage data-latex="{\textwidth}"}
## Additional Functions {#additional-functions .unnumbered}

Along with constants and the dataset-related functions, other functions are also available.
These functions can be used in a dataset's formulas section, the `"constants"` section, and even in-place (e.g., in a label's text value).

- ``ReportName()``: Returns the report's name.
- ``PageNumber()``: Returns the current page number.
- ``Now(`value`)``: Returns the current date and time (or date component).
    - *value*: the part of today's date to return (if not provided, then the full date is returned). \
      The following options are available:
      - `` `Year` ``: The year.
      - `` `Day` ``: The day of the month.
      - `` `DayName` ``: The day of the month as a name (e.g., Tuesday).
      - `` `Month` ``: The numeric value of the month.
      - `` `MonthName` ``: The name of the month.
      - `` `MonthShortName` ``: The abbreviated name of the month.
      - `` `Fancy` ``: The date formatted as full month name, day, and four-digit year.
:::
