# (PART) Graph Properties {-}

# Common Graph Properties

The following section details properties common to all graphs.

## Base-level Graph Properties {#graph-properties -}

Properties common to all graphs:

- `"dataset"`: if the object requires a dataset (most graphs do), then this is the name of the dataset.<br />
     Note that this is the unique name of the dataset loaded from the report's
     [datasets](#datasets-properties) section, not a filepath.<br />
     Also, this is optional if the item type doesn't require a dataset (e.g., a `Wisteria::GraphItems::Label`).
- `"title"`: the title of the graph, which contains [label](#label-properties) properties.
- `"sub-title"`: the subtitle of the graph, which contains [label](#label-properties) properties.
- `"caption"`: the caption of the graph, which contains [label](#label-properties) properties.
- `"axes"`: an array of [axis](#axis-properties) objects.
- `"background-color"`: a string specifying the plotting area's background color.
- `"image-scheme"`: an array of image import specifications. (See [image file properties](#image-file-properties).)
- `"common-box-image-outline"`: string specifying the color for the outline around the bars/boxes
     if using a common box image.
- `"stipple-image"`: an image import specification. (See [image file properties](#image-file-properties).)
- `"annotations"`: text messages that can be added on top of the graph, optionally pointing to positions
  on the graph. This is an array of annotation definitions, which contain the following properties:
  - `"label"`: the label for the note, which contains [label](#label-properties) properties.
  - `"interest-points"`: The points that the note will point at.<br />
    This is an array of items which contain the following properties:
    - `"x"`: the X axis position of the point.
    - `"y"`: the Y axis position of the point.
  - `"anchor"`: the point to anchor the label.<br />
     Note that the `label`'s `"anchoring"` property will control which part of the label that the
     anchoring point refers to.<br />
     If not specified, the graph will attempt to place it at the best location.<br />
     This contains the following properties:
     - `"x"`: the X axis position of the point.
     - `"y"`: the Y axis position of the point.
- `"reference-lines"`: an array of reference line definitions, which contain the following properties:
  - `"axis-type"`: the axis to add the reference line to.<br />
    Available options are:
    - `"bottom-x"`
    - `"right-y"`
    - `"left-y"`
    - `"top-y"`
  - `"position"`: the axis position for the line.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"label"`: the text to display on the legend referring to line.
  - `"pen"`: the definition for the [pen](#pen-properties) properties.
- `"reference-areas"`: an array of reference area definitions, which contain the following properties:
  - `"axis-type"`: the axis to add the reference area to.<br />
    Available options are:
    - `"bottom-x"`
    - `"right-y"`
    - `"left-y"`
    - `"top-y"`
  - `"start"`: the starting axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"end"`: the ending axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"label"`: the text to display on the legend referring to area.
  - `"pen"`: the definition for the [pen](#pen-properties) properties.<br />
        The color is used for the surrounding reference lines, and a tinted version
        is used the area.
  - `"style"`: the style to apply to the reference area.<br />
    Available options are:
    - `"fade-from-left-to-right"`
    - `"fade-from-right-to-left"`
    - `"solid"`
- `"brush-scheme"`: for graphs that support brush schemes only.<br />
     Contains the following properties:
     `"brush-styles"`: an array of strings specifying the [brush styles](#brush-properties).
     `"color-scheme"`: a color scheme that is mapped to the brush styles.
     This can also be a string specifying a named color scheme (e.g., `"icecream"`).
- `"color-scheme"`: for graphs that support color schemes only.<br />
     This can either be an array of color strings or the name of the color scheme.<br />
     Refer to `Wisteria::Colors::Schemes` for a list of color schemes.
- `"icon-scheme"`: for graphs that support icon/marker schemes only.<br />
  This an either be an icon scheme name or an array of icon strings (which can be recycled)<br />
  Refer to `Wisteria::Icons::Schemes` for a list of icon schemes.<br />
  The following individual icons are available:
  - `"blank"`
  - `"horizontal-line"`
  - `"arrow-right"`
  - `"circle"`
  - `"image"`
  - `"horizontal-separator"`
  - `"horizontal-arrow-right-separator"`
  - `"color-gradient"`
  - `"square"`
  - `"triangle-upward"`
  - `"triangle-downward"`
  - `"triangle-right"`
  - `"triangle-left"`
  - `"diamond"`
  - `"plus"`
  - `"asterisk"`
  - `"hexagon"`
  - `"box-plot"`
  - `"location-marker"`
  - `"go-road-sign"`
  - `"warning-road-sign"`
  - `"sun"`
  - `"flower"`
  - `"fall-leaf"`
  - `"top-curly-brace"`
  - `"right-curly-brace"`
  - `"bottom-curly-brace"`
  - `"left-curly-brace"`
  - `"man"`
  - `"woman"`
  - `"business-woman"`
  - `"chevron-downward"`
  - `"chevron-upward"`
  - `"text"`
  - `"tack"`
  - `"banner"`
  - `"watercolor-rectangle"`
- `"line-scheme"`: for graphs that support line schemes only.<br />
  This is an array of line specifications (which can be recycled)<br />
  Each specification contains the following:
  - `"line-style"`: a string specifying the line style.<br />
    Available options are:
    - `"lines"`
    - `"arrows"`
    - `"spline"`
  - `"pen-style"`: a [pen](#pen-properties) specificaiton (although only the pen style is used)
- `"legend"`: an item containing the following properties:
  - `"placement"`: where to place the legend.<br />
    Available options are:
    - `"left"`
    - `"right"` (the default)
    - `"top"`
    - `"bottom"`
  - `"include-header"`: `true` to include a header (the default), `false` to not.
  - `"title"`: if `"include-header"` is `true`, a string specifying the title of the legend.
  - `"ring"`: for pie charts, which ring to use for the legend.<br />
    Available options are:
    - `"outer"`: only the outer (or only) ring is included. (This is the default.)
    - `"inner"`: the inner and outer rings are included in the legend.

# Common Graph Features

The following section details properties relevant to graphs and tables.

## Pen {#pen-properties .unnumbered}

Properties for pens:

- `"color"`: the pen color. This can be either a color name or hex-encoded value.
- `"width"`: the width of the pen's line.
- `"style"`: the pen's style, which includes the following:
  - `"dot"`
  - `"dot-dash"`
  - `"long-dot"`
  - `"short-dot"`
  - `"solid"` (the default)
  - `"cross-hatch"`
  - `"horizontal-hatch"`
  - `"vertical-hatch"`

Note that a pen can be set to `null` to turn it off.

## Brush {#brush-properties .unnumbered}

Properties for brushes:

- `"color"`: the brush color. This can be either a color name or hex-encoded value.
- `"style"`: the brush's pattern, which includes the following:
  - `"backwards-diagonal-hatch"`
  - `"forward-diagonal-hatch"`
  - `"cross-diagonal-hatch"`
  - `"solid"` (the default)
  - `"cross-hatch"`
  - `"horizontal-hatch"`
  - `"vertical-hatch"`

Note that brushes can be set to `null` to turn it off.

Also, instead of properties, a single string can be specified indicating color for the brush.

## Image Files {#image-file-properties .unnumbered}

Properties for image import specifications:

- `"paths"`: an array of file paths to import for the image.
- `"color-filter"`: a string specifying a color to translucently apply across the image.
- `"opacity"`: a number between `0-255` specifying how opaque the image is.<br />
  Note that when loading an image for a page's background, this value will be overridden
  by the page's background opacity setting.
- `"stitch"`: string specifying how to stitch multiple images together.<br />
  Available options are:
  - `"vertical"`
  - `"horizontal"` (the default)

Note that instead of properties, a single string can be specified indicating a file path to load.

## Axis {#axis-properties .unnumbered}

`"axes"` nodes can either be part of a graph node definition or a [common-axis](#common-axis-properties) node.<br />
  For the former, this can define properties for the various axes in the graph.<br />
  `"axes"`: nodes contain an array of axis objects, each with the following properties:

- `"axis-type"`: the type of axis.<br />
  Available options are:
  - `"bottom-x"`
  - `"right-y"`
  - `"left-y"`
  - `"top-y"`
- `"title"`: the title of the axis, which contains [label](#label-properties) properties.
- `"axis-pen"`: the pen for the axis line, which includes [pen](#pen-properties) properties.
- `"gridline-pen"`: the pen for the gridlines, which includes [pen](#pen-properties) properties.
- `"double-sided-labels"`: boolean value specifying whether axis labels should be shown on both sides of the axis.
- `"tickmarks"`: tickmarks settings, which contains the following properties:
  - `"display"`: a string, indicating how to display the tickmarks.<br />
    Available options are:
    - `"inner"`
    - `"outer"`
    - `"crossed"`
    - `"no-display"`
- `"label-display"`: what to display for the labels along the axis.<br />
  Available options are:
  - `"custom-labels-or-values"`
  - `"only-custom-labels"`
  - `"custom-labels-and-values"`
  - `"no-display"`
- `"show-outer-labels"`: `true` to show the outer labels on the axis.
- `"label-length"`: a number specifying the suggested maximum length for the axis labels. (Default is 100.)
- `"label-length-auto"`: if `true`, an attempt will be made to split longer axis labels based on
     various separators in them (e.g., parentheses, commas, conjunctions).

- `"brackets"`: adds brackets to the axis,which can be an array of bracket definitions or single set of properties
  using a dataset.<br />
  Available options for either method are:
  - `"simplify"`: a boolean value indicating whether to simplify the bracket's labels.
 
  If building brackets from a dataset, use the following properties:
  - `"dataset"`: the name of the dataset to read the columns from.<br />
       Note that this dataset can be different from the dataset used for the first
       child graph if you are wanting to use different labels. For this situation, the
       `"value"` variable should have the same scale as the child graph.
  - `"variables"`: which include the following properties:
    - `"label"`: the labels column.
    - `"value"`: the values column. (This can be either a continous, categorical, or date column.)
  - `"pen"`: the bracket line, which includes [pen](#pen-properties) properties.
  - `"style"`: the style of the braces.<br />
    Available options are:
    - `"arrow"`
    - `"reverse-arrow"`
    - `"lines"`
    - `"curly-braces"`
    - `"no-connection-lines"`
  
  If building brackets individually, specify an area of items, each with the following properties:
  - `"start"`: the starting axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"end"`: the ending axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"label"`: the text to display on next to the brackets.
  - `"pen"`: the bracket line, which includes [pen](#pen-properties) properties.
  - `"style"`: the style of the braces.<br />
    Available options are:
    - `"arrow"`
    - `"reverse-arrow"`
    - `"lines"`
    - `"curly-braces"` (the default)
    - `"no-connection-lines"`

## Positions {#position-properties .unnumbered}

Properties for row or column table positions:

- `"origin"`: this is either the zero-based index of the row/column, or a string.<br />
     The string values available are `"last-row"` or `"last-column"`,
     which will be interpreted as the last row or column in the data, respectively.<br />
     Column names from the dataset can also be used if looking for a column position.
- `"offset"`: a numeric value combined with the value for `"origin"`.<br />
     This is optional and is useful for when `"origin"` is interpreted at runtime.<br />
     For example, if `origin` is `"last-row"`: and `"offset"` is `-1`, then this will
     result in the second-to-last row.

A position can also be a number if not needing to use the `"origin"`/`"offset"` features.

# Base-level Graphs

The following are properties relevant to specific graphs' base-level graph type.

## Bar Chart {#bar-chart-properties .unnumbered}

Properties common to all bar-chart derived graphs:

- `"box-effect"`: string specifying the effects for the bars.
  Available options are:
  - `"common-image"` (This will require an `"image-scheme"` to be defined.)
  - `"fade-from-bottom-to-top"`
  - `"fade-from-left-to-right"`
  - `"fade-from-right-to-left"`
  - `"fade-from-top-to-bottom"`
  - `"glassy"`
  - `"solid"` (the default)
  - `"stipple"`
  - `"watercolor"`
- `"bar-label-display"`: string specifying how to display labels on the bars.
  Available options are:
  - `"percentage"`
  - `"value"`
  - `"value-and-percentage"`
  - `"no-display"`
  - `"bin-name"`
  - `"bin-name-and-value"`
  - `"bin-name-and-percentage"`
- `"include-spaces-between-bars"`: `true` to include spaces between bars.
- `"ghost-opacity"`: number specifying the opacity level of non-showcased bars.
- `"showcase-bars"`: an array of strings specifying which bars to showcase.
- `"bar-icons"`: an array of bar icon specifications. Each specification contains the following:
  - `"label"`: the label of the bar to add an icon to.
  - `"image"`: the path to the image to add to the bar label.
- `"bar-sort"`: properties specifying how to sort the bars (after loading the data).
  Available options are:
  - `"direction"`
    Available options are:
    - `"ascending"`
    - `"descending"`
  - `"by"`: how to sort the bars, by label or length. This will override any `"labels"` option.
    Available options are:
    - `"length"`
    - `"label"`
  - `"labels"`: the bar labels, specified in the order they should be sorted.<br />
       If `"direction"` is `"ascending"`, then the bars will be sorted top-to-bottom or
       left-to-right (based on the order of the provided labels). Otherwise, they will be
       sorted bottom-to-top or right-to-left.<br />
       Note that this option is ignored if `"by"` is specified.
- `"bar-groups"`: an array of bar groups, each containing the following properties:
  - `"start"`: the axis label or numeric position to start the group.
  - `"end"`: the axis label or numeric position to end the group.
  - `"decal"`: a label to display on the group bar.
  - `"brush"`: the brush to paint with, which includes [brush](#brush-properties) properties.
  - `"color"`: the base color to paint under the brush. This is useful if the brush is using a hatch pattern.
- `"decals"`: an array of decals to add to the bars. This will be an array of nodes containing the following properties:
  - `"bar"`: the axis label of the bar.
  - `"block"`: number specifying which block in the bar to add the decal to. If not specified, defaults to `0`.
  - `"decal"`: the decal to add to the bar, which will contain [label](#label-properties) properties.
- `"first-bar-brackets"`: properties adding axis brackets that reference the first bar.
  Available options are:
  - `"label"`: string for the bracket's label.
  - `"start-block-re"`: a regular expression used to find the starting block for the bracket.
  - `"end-block-re"`: a regular expression used to find the ending block for the bracket.

  If the `"re"` variations of the starting and ending labels are available, then these properties are used:
  - `"start-block"`: string specifying the tag of the starting block of the bar.
  - `"end-block"`: string specifying the tag of the ending block of the bar.
- `"constrain-scaling-axis-to-bars"`: `true` to force the scaling axis to the longest bar.

Note that bar sorting is performed prior to adding bar groups. When specifying the start and end of your bar groups,
any bar sorting that you specified will be in effect. Likewise, axis brackets are also added after the bars are sorted;
if specifying start and end points for your brackets, be aware that the bars will already be sorted.