# Base-level Properties

## Axis {#axis-properties}

`"axes"` nodes can either be part of a graph node definition or a ["common-axis"](#common-axis-properties) node.<br />
  For the former, this can define properties for the various axes in the graph.<br />
  `"axes"` nodes contain an array of axis objects, each with the following properties:

- `"axis-type"`: the type of axis.<br />
  Available options are:
  - `"bottom-x"`
  - `"right-y"`
  - `"left-y"`
  - `"top-y"`
- `"title"`: the title of the axis, which contains ["label"](#label-properties) properties.
- `"axis-pen"`: the pen for the axis line, which includes [pen](#pen-properties) properties.
- `"gridline-pen"`: the pen for the gridlines, which includes [pen](#pen-properties) properties.
- `"double-sided-labels"`: boolean value specifying whether axis labels should be shown on both sides of the axis.
- `"tickmarks"`: tickmarks settings, which contains the following properties:
  - `"display"`: a string, indicating how to display the tickmarks.<br />
    Available options are:
    - `"inner"`
    - `"outer"`
    - `"crossed"`
    - `"no-display"`
- `"label-display"`: what to display for the labels along the axis.<br />
  Available options are:
  - `"custom-labels-or-values"`
  - `"only-custom-labels"`
  - `"custom-labels-and-values"`
  - `"no-display"`
- `"show-outer-labels"`: `true` to show the outer labels on the axis.
- `"label-length"`: a number specifying the suggested maximum length for the axis labels. (Default is 100.)
- `"label-length-auto"` if `true`, an attempt will be made to split longer axis labels based on
     various separators in them (e.g., parentheses, commas, conjunctions).

- `"brackets"`: adds brackets to the axis,which can be an array of bracket definitions or single set of properties
  using a dataset.<br />
  Available options for either method are:
  - `"simplify"`: a boolean value indicating whether to simplify the bracket's labels.
 
  If building brackets from a dataset, use the following properties:
  - `"dataset"`: the name of the dataset to read the columns from.<br />
       Note that this dataset can be different from the dataset used for the first
       child graph if you are wanting to use different labels. For this situation, the
       `"value"` variable should have the same scale as the child graph.
  - `"variables"` which include the following properties:
    - `"label"`: the labels column.
    - `"value"`: the values column. (This can be either a continous, categorical, or date column.)
  - `"pen"`: the bracket line, which includes [pen](#pen-properties) properties.
  - `"style"`: the style of the braces.<br />
    Available options are:
    - `"arrow"`
    - `"reverse-arrow"`
    - `"lines"`
    - `"curly-braces"`
    - `"no-connection-lines"`
  
  If building brackets individually, specify an area of items, each with the following properties:
  - `"start"`: the starting axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"end"`: the ending axis position for the area.<br />
       This can either be a numeric position, a date (as a string), or an axis label.
  - `"label"`: the text to display on next to the brackets.
  - `"pen"`: the bracket line, which includes [pen](#pen-properties) properties.
  - `"style"`: the style of the braces.<br />
    Available options are:
    - `"arrow"`
    - `"reverse-arrow"`
    - `"lines"`
    - `"curly-braces"` (the default)
    - `"no-connection-lines"`

## Positions {#position-properties}

Properties for row or column positions:

- `"origin"`: this is either the zero-based index of the row/column, or a string.<br />
     The string values available are `"last-row"` or `"last-column"`,
     which will be interpreted as the last row or column in the data, respectively.<br />
     Column names from the dataset can also be used if looking for a column position.
- `"offset"`: a numeric value combined with the value for `"origin"`.<br />
     This is optional and is useful for when `"origin"` is interpreted at runtime.<br />
     For example, if `origin` is `"last-row"`: and `offset` is `-1`, then this will
     result in the second-to-last row.

A position can also be a number if not needing to use the `"origin"`/`"offset"` features.

## Pen {#pen-properties}

Properties for pens:

- `"color"`: the pen color. This can be either a color name or hex-encoded value.
- `"width"`: the width of the pen's line.
- `"style"`: the pen's style, which includes the following:
  - `"dot"`
  - `"dot-dash"`
  - `"long-dot"`
  - `"short-dot"`
  - `"solid"` (the default)
  - `"cross-hatch"`
  - `"horizontal-hatch"`
  - `"vertical-hatch"`

Note that a pen can be set to `null` to turn it off.

## Brush {#brush-properties}

Properties for brushes:

- `"color"`: the brush color. This can be either a color name or hex-encoded value.
- `"style"`: the brush's pattern, which includes the following:
  - `"backwards-diagonal-hatch"`
  - `"forward-diagonal-hatch"`
  - `"cross-diagonal-hatch"`
  - `"solid"` (the default)
  - `"cross-hatch"`
  - `"horizontal-hatch"`
  - `"vertical-hatch"`

Note that brushes can be set to `null` to turn it off.
