## All Items {#item-properties}

Properties common to all items:

- `"id"`: a (unique) numeric identifier for the item. This can be referenced by other items in the report.<br />
     An example can be adding an ID to a graph and then inserted a ["common-axis"](#common-axis-properties) to the
     report that accepts this ID.
- `"canvas-margins"`: a numeric array (one to four numbers), representing the item's canvas margin going clockwise,
     starting at 12 o'clock.
- `"padding"`: a numeric array (one to four numbers), representing the item's padding going clockwise,
     starting at 12 o'clock.
- `"pen"`: the item's pen, which includes [pen](#pen-properties) properties.
- `"outline"`: a boolean array, specifying the item's border outlines to draw going clockwise,
     starting at 12 o'clock. Note that `"pen"` must be valid and that this is not supported by all objects.
- `"scaling"` numeric value of how much to scale the object's size. For example, `2.0` will double the
     its default size.
- `"show"` boolean value specifying whether to show the item.
- `"anchoring"` controls the starting point of where the object is drawn.<br />
  This is usually only relative for objects being embedded on a plot (e.g., annotations).<br />
  Available options are:
  - `"bottom-left-corner"`
  - `"bottom-right-corner"`
  - `"center"` (the default)
  - `"top-left-corner"`
  - `"top-right-corner"`
- `"relative-alignment"` how an object is aligned with its parent (e.g., an axis title relative to its axis).<br />
  Available options are:
  - `"flush-left"`
  - `"flush-right"`
  - `"flush-top"`
  - `"flush-bottom"`
  - `"centered"`
- `"horizontal-page-alignment"` how to horizontally align the item within its area.<br />
  Available options are:
  - `"left-aligned"`
  - `"right-aligned"`
  - `"centered"`
- `"vertical-page-alignment"` how to vertically align the item within its area.<br />
  Available options are:
  - `"top-aligned"`
  - `"bottom-aligned"`
  - `"centered"`
- `"fit-row-to-content"`: a boolean value specifying whether the item's calculated height should
     control how tall its canvas row is.
- `"fixed-width"`: a boolean value specifying whether the item should be constrained
     to its calculated width within its row.

# Notes {#notes}

Color values can either be hex encoded (e.g., `"#FF0000"` for red) or a named value (`"pumpkin"`). For a full list
of color names available, refer to the `Wisteria::Colors::Color` enumeration. Specifying `null` for a color
will result in a transparent color.