# Automatically generated from 'ListFiles.cmake'
# This should be used for the application build.
# DO NOT MODIFY MANUALLY!

SET(APP_WISTERIA_SRC
    src/app/appsettings.cpp
    src/app/wisteriaapp.cpp
    src/app/wisteriadoc.cpp
    src/app/wisteriaview.cpp
    src/base/axis.cpp
    src/base/brushes.cpp
    src/base/canvas.cpp
    src/base/colorbrewer.cpp
    src/base/colorlookup.cpp
    src/base/colors.cpp
    src/base/commonaxisbuilder.cpp
    src/base/fillableshape.cpp
    src/base/graphitems.cpp
    src/base/icons.cpp
    src/base/image.cpp
    src/base/label.cpp
    src/base/lines.cpp
    src/base/pdfreportprintout.cpp
    src/base/points.cpp
    src/base/polygon.cpp
    src/base/report_builder_forumulas.cpp
    src/base/reportbuilder.cpp
    src/base/reportbuildercolors.cpp
    src/base/reportprintout.cpp
    src/base/reporttableloader.cpp
    src/base/shapes.cpp
    src/base/shapes_art.cpp
    src/base/shapes_buildings.cpp
    src/base/shapes_business.cpp
    src/base/shapes_education.cpp
    src/base/shapes_food.cpp
    src/base/shapes_geometric.cpp
    src/base/shapes_medical.cpp
    src/base/shapes_nature.cpp
    src/base/shapes_people.cpp
    src/base/shapes_religion.cpp
    src/base/shapes_stats.cpp
    src/base/shapes_vehicles.cpp
    src/base/svgreportprintout.cpp
    src/data/clone.cpp
    src/data/dataset.cpp
    src/data/excelreader.cpp
    src/data/join_inner.cpp
    src/data/join_left.cpp
    src/data/odsreader.cpp
    src/data/pivot.cpp
    src/data/subset.cpp
    src/data/textclassifier.cpp
    src/debug/debug_profile.cpp
    src/easyexif/exif.cpp
    src/graphs/barchart.cpp
    src/graphs/boxplot.cpp
    src/graphs/bubbleplot.cpp
    src/graphs/candlestickplot.cpp
    src/graphs/categoricalbarchart.cpp
    src/graphs/chernoffplot.cpp
    src/graphs/crawfordgraph.cpp
    src/graphs/danielsonbryan2plot.cpp
    src/graphs/fleschchart.cpp
    src/graphs/ganttchart.cpp
    src/graphs/graph2d.cpp
    src/graphs/groupgraph2d.cpp
    src/graphs/heatmap.cpp
    src/graphs/histogram.cpp
    src/graphs/inflesz.cpp
    src/graphs/likertchart.cpp
    src/graphs/lineplot.cpp
    src/graphs/lixgauge.cpp
    src/graphs/lixgaugegerman.cpp
    src/graphs/lrroadmap.cpp
    src/graphs/multi_series_lineplot.cpp
    src/graphs/piechart.cpp
    src/graphs/proconroadmap.cpp
    src/graphs/roadmap.cpp
    src/graphs/sankeydiagram.cpp
    src/graphs/scalechart.cpp
    src/graphs/scatterplot.cpp
    src/graphs/stemandleafplot.cpp
    src/graphs/table.cpp
    src/graphs/waffle_chart.cpp
    src/graphs/wcurveplot.cpp
    src/graphs/win_loss_sparkline.cpp
    src/graphs/wordcloud.cpp
    src/import/spreadsheet_extract_text.cpp
    src/import/xlsx_extract_text.cpp
    src/ui/app.cpp
    src/ui/controls/listctrlex.cpp
    src/ui/controls/listctrlexcelexporter.cpp
    src/ui/controls/listctrlexdataprovider.cpp
    src/ui/controls/searchpanel.cpp
    src/ui/controls/sidebar.cpp
    src/ui/controls/sidebarbook.cpp
    src/ui/controls/thumbnail.cpp
    src/ui/dialogs/datasetimportdlg.cpp
    src/ui/dialogs/editors/accessibilityoptionspanel.cpp
    src/ui/dialogs/editors/axisoptionspanel.cpp
    src/ui/dialogs/editors/insertboxplotdlg.cpp
    src/ui/dialogs/editors/insertbubbleplotdlg.cpp
    src/ui/dialogs/editors/insertcandlestickplotdlg.cpp
    src/ui/dialogs/editors/insertcatbarchartdlg.cpp
    src/ui/dialogs/editors/insertchernoffdlg.cpp
    src/ui/dialogs/editors/insertcommonaxisdlg.cpp
    src/ui/dialogs/editors/insertganttchartdlg.cpp
    src/ui/dialogs/editors/insertgraphdlg.cpp
    src/ui/dialogs/editors/insertheatmapdlg.cpp
    src/ui/dialogs/editors/inserthistogramdlg.cpp
    src/ui/dialogs/editors/insertimgdlg.cpp
    src/ui/dialogs/editors/insertitemdlg.cpp
    src/ui/dialogs/editors/insertlabeldlg.cpp
    src/ui/dialogs/editors/insertlikertdlg.cpp
    src/ui/dialogs/editors/insertlineplotdlg.cpp
    src/ui/dialogs/editors/insertlrroadmapdlg.cpp
    src/ui/dialogs/editors/insertmultiserieslineplotdlg.cpp
    src/ui/dialogs/editors/insertpagedlg.cpp
    src/ui/dialogs/editors/insertpiechartdlg.cpp
    src/ui/dialogs/editors/insertproconroadmapdlg.cpp
    src/ui/dialogs/editors/insertsankeydiagramdlg.cpp
    src/ui/dialogs/editors/insertscalechartdlg.cpp
    src/ui/dialogs/editors/insertscatterplotdlg.cpp
    src/ui/dialogs/editors/insertshapedlg.cpp
    src/ui/dialogs/editors/insertstemandleafdlg.cpp
    src/ui/dialogs/editors/inserttabledlg.cpp
    src/ui/dialogs/editors/insertwafflechartdlg.cpp
    src/ui/dialogs/editors/insertwcurvedlg.cpp
    src/ui/dialogs/editors/insertwlsparklinedlg.cpp
    src/ui/dialogs/editors/insertwordclouddlg.cpp
    src/ui/dialogs/editors/joindlg.cpp
    src/ui/dialogs/editors/pivotlongerdlg.cpp
    src/ui/dialogs/editors/pivotwiderrdlg.cpp
    src/ui/dialogs/editors/subsetdlg.cpp
    src/ui/dialogs/excelpreviewdlg.cpp
    src/ui/dialogs/gridexportdlg.cpp
    src/ui/dialogs/imageexportdlg.cpp
    src/ui/dialogs/imagemergedlg.cpp
    src/ui/dialogs/listctrlitemviewdlg.cpp
    src/ui/dialogs/listctrlsortdlg.cpp
    src/ui/dialogs/listdlg.cpp
    src/ui/dialogs/odspreviewdlg.cpp
    src/ui/dialogs/opacitydlg.cpp
    src/ui/dialogs/pdfexportdlg.cpp
    src/ui/dialogs/printerheaderfooterdlg.cpp
    src/ui/dialogs/projectsettingsdlg.cpp
    src/ui/dialogs/radioboxdlg.cpp
    src/ui/dialogs/svgexportdlg.cpp
    src/ui/dialogs/variableselectdlg.cpp
    src/ui/dialogs/warningmessagesdlg.cpp
    src/ui/mainframe.cpp
    src/util/downloadfile.cpp
    src/util/fileutil.cpp
    src/util/formulaformat.cpp
    src/util/hardwareinfo.cpp
    src/util/i18n_string_util.cpp
    src/util/logfile.cpp
    src/util/memorymappedfile.cpp
    src/util/resource_manager.cpp
    src/util/textreplace.cpp
    src/util/textstream.cpp
    src/util/warningmanager.cpp
    src/util/xml_format.cpp
    src/util/zipcatalog.cpp
    src/wxSimpleJSON/src/cJSON/cJSON.c
    src/wxSimpleJSON/src/wxSimpleJSON.cpp
    src/wxStartPage/startpage.cpp)