images/axis.svg
images/barchart-image.svg
images/barchart-serpentine-aggressive.svg
images/barchart-serpentine.svg
images/barchart-stylized.svg
images/barchart.svg
images/boxplot.svg
images/bubbleplot.svg
images/bulletchart.svg
images/candlestick.svg
images/categorical.svg
images/chart-basic.svg
images/chart-business.svg
images/chart-education.svg
images/chart-social.svg
images/chart-sports.svg
images/chart-statistical.svg
images/chart-survey.svg
images/chernoffplot.svg
images/choropleth.svg
images/clear.svg
images/color-wheel.svg
images/constants-add.svg
images/constants-delete.svg
images/constants.svg
images/copy.svg
images/dashboard.svg
images/data-add.svg
images/data-delete.svg
images/data-edit.svg
images/data.svg
images/date.svg
images/delete.svg
images/dichotomous-categorical.svg
images/dichotomous-discrete.svg
images/discrete.svg
images/divider-horizontal-double.svg
images/divider-horizontal-single.svg
images/divider-vertical-double.svg
images/divider-vertical-single.svg
images/donut-subgrouped.svg
images/donut.svg
images/dubois-spiral.svg
images/edit.svg
images/equals.svg
images/file-open.svg
images/file-save.svg
images/find.svg
images/funnel.svg
images/gantt.svg
images/group.svg
images/heatmap-grouped.svg
images/heatmap.svg
images/histogram.svg
images/home-dark-mode.svg
images/home.svg
images/image.svg
images/join.svg
images/kpi-card.svg
images/label.svg
images/likert3.svg
images/likert7.svg
images/lineplot-points.svg
images/lineplot.svg
images/log-book.svg
images/multiplot-common-axis.svg
images/multiplot.svg
images/page-add.svg
images/page-delete.svg
images/page-edit.svg
images/page.svg
images/paste.svg
images/pdf.svg
images/pictograph.svg
images/piechart-subgrouped.svg
images/piechart.svg
images/pivot-longer.svg
images/pivot-wider.svg
images/powerpoint.svg
images/print-setup.svg
images/print.svg
images/project-settings.svg
images/question-mark.svg
images/racetrack.svg
images/realtime.svg
images/reload.svg
images/report.svg
images/roadmap.svg
images/rose.svg
images/sankey.svg
images/scale.svg
images/scatterplot.svg
images/select-all.svg
images/shape.svg
images/sort.svg
images/spacer.svg
images/sparkline.svg
images/stem-leaf.svg
images/subset.svg
images/table.svg
images/waffle.svg
images/waterfallchart.svg
images/wcurve.svg
images/wilmarth-bridge.svg
images/wisteria.svg
images/wordcloud.svg