barchart-image.svg
barchart-stylized.svg
barchart.svg
boxplot.svg
bubbleplot.svg
candlestick.svg
categorical.svg
chart-basic.svg
chart-business.svg
chart-education.svg
chart-social.svg
chart-sports.svg
chart-statistical.svg
chart-survey.svg
chernoffplot.svg
clear.svg
color-wheel.svg
constants-add.svg
constants-delete.svg
constants.svg
copy.svg
data-add.svg
data-delete.svg
data.svg
date.svg
delete.svg
dichotomous-categorical.svg
dichotomous-discrete.svg
discrete.svg
donut-subgrouped.svg
donut.svg
edit.svg
equals.svg
file-open.svg
file-save.svg
find.svg
gantt.svg
group.svg
heatmap-grouped.svg
heatmap.svg
histogram.svg
home-dark-mode.svg
home.svg
image.svg
join.svg
label.svg
likert3.svg
likert7.svg
lineplot-points.svg
lineplot.svg
log-book.svg
multiplot-common-axis.svg
multiplot.svg
page-add.svg
page-delete.svg
page-edit.svg
page.svg
piechart-subgrouped.svg
piechart.svg
pivot-longer.svg
pivot-wider.svg
print.svg
question-mark.svg
realtime.svg
reload.svg
roadmap.svg
sankey.svg
scale.svg
scatterplot.svg
select-all.svg
shape.svg
sort.svg
sparkline.svg
stem-leaf.svg
subset.svg
table.svg
waffle.svg
wcurve.svg
wisteria.svg
wordcloud.svg