barchart-image.svg
barchart-stylized.svg
barchart.svg
boxplot.svg
bubbleplot.svg
candlestick.svg
categorical.svg
chart-basic.svg
chart-business.svg
chart-education.svg
chart-social.svg
chart-sports.svg
chart-statistical.svg
chart-survey.svg
chernoffplot.svg
data.svg
date.svg
dichotomous-categorical.svg
dichotomous-discrete.svg
discrete.svg
donut-subgrouped.svg
donut.svg
file-open.svg
gantt.svg
heatmap-grouped.svg
heatmap.svg
histogram.svg
home-dark-mode.svg
home.svg
likert3.svg
likert7.svg
lineplot-points.svg
lineplot.svg
multiplot-common-axis.svg
multiplot.svg
page.svg
piechart-subgrouped.svg
piechart.svg
print.svg
roadmap.svg
sankey.svg
scale.svg
scatterplot.svg
sparkline.svg
stem-leaf.svg
table.svg
waffle.svg
wcurve.svg
wisteria.svg
wordcloud.svg