# Automatically generated from 'Build CMake Files List.R'
# DO NOT MODIFY MANUALLY!

SET(WISTERIA_SRC
    src/base/axis.cpp
    src/base/canvas.cpp
    src/base/colorbrewer.cpp
    src/base/colors.cpp
    src/base/commonaxisbuilder.cpp
    src/base/fillableshape.cpp
    src/base/graphitems.cpp
    src/base/image.cpp
    src/base/label.cpp
    src/base/lines.cpp
    src/base/points.cpp
    src/base/polygon.cpp
    src/base/reportbuilder.cpp
    src/base/reportbuildercolors.cpp
    src/base/reportprintout.cpp
    src/base/shapes.cpp
    src/data/clone.cpp
    src/data/dataset.cpp
    src/data/join.cpp
    src/data/pivot.cpp
    src/data/subset.cpp
    src/data/textclassifier.cpp
    src/debug/debug_profile.cpp
    src/easyexif/demo.cpp
    src/easyexif/exif.cpp
    src/graphs/barchart.cpp
    src/graphs/boxplot.cpp
    src/graphs/candlestickplot.cpp
    src/graphs/categoricalbarchart.cpp
    src/graphs/ganttchart.cpp
    src/graphs/graph2d.cpp
    src/graphs/heatmap.cpp
    src/graphs/histogram.cpp
    src/graphs/likertchart.cpp
    src/graphs/lineplot.cpp
    src/graphs/lrroadmap.cpp
    src/graphs/piechart.cpp
    src/graphs/proconroadmap.cpp
    src/graphs/roadmap.cpp
    src/graphs/table.cpp
    src/graphs/wcurveplot.cpp
    src/ui/app.cpp
    src/ui/imageexportdlg.cpp
    src/ui/mainframe.cpp
    src/ui/opacitydlg.cpp
    src/ui/printerheaderfooterdlg.cpp
    src/ui/radioboxdlg.cpp
    src/ui/thumbnail.cpp
    src/ui/variableselectdlg.cpp
    src/util/formulaformat.cpp
    src/util/logfile.cpp
    src/util/memorymappedfile.cpp
    src/util/textreplace.cpp
    src/wxSimpleJSON/src/cJSON/cJSON.c
    src/wxSimpleJSON/src/wxSimpleJSON.cpp)