# Automatically generated from 'build_cmake_files_list.R'
# This should be used for the unit test runner.
# DO NOT MODIFY MANUALLY!

SET(WISTERIA_SRC
    ../../src/base/axis.cpp
    ../../src/base/canvas.cpp
    ../../src/base/colorbrewer.cpp
    ../../src/base/colors.cpp
    ../../src/base/commonaxisbuilder.cpp
    ../../src/base/fillableshape.cpp
    ../../src/base/graphitems.cpp
    ../../src/base/image.cpp
    ../../src/base/label.cpp
    ../../src/base/lines.cpp
    ../../src/base/points.cpp
    ../../src/base/polygon.cpp
    ../../src/base/reportbuilder.cpp
    ../../src/base/reportbuildercolors.cpp
    ../../src/base/reportprintout.cpp
    ../../src/base/shapes.cpp
    ../../src/data/clone.cpp
    ../../src/data/dataset.cpp
    ../../src/data/excelreader.cpp
    ../../src/data/join.cpp
    ../../src/data/pivot.cpp
    ../../src/data/subset.cpp
    ../../src/data/textclassifier.cpp
    ../../src/debug/debug_profile.cpp
    ../../src/easyexif/exif.cpp
    ../../src/graphs/barchart.cpp
    ../../src/graphs/boxplot.cpp
    ../../src/graphs/candlestickplot.cpp
    ../../src/graphs/categoricalbarchart.cpp
    ../../src/graphs/crawfordgraph.cpp
    ../../src/graphs/danielsonbryan2plot.cpp
    ../../src/graphs/fleschchart.cpp
    ../../src/graphs/ganttchart.cpp
    ../../src/graphs/graph2d.cpp
    ../../src/graphs/groupgraph2d.cpp
    ../../src/graphs/heatmap.cpp
    ../../src/graphs/histogram.cpp
    ../../src/graphs/inflesz.cpp
    ../../src/graphs/likertchart.cpp
    ../../src/graphs/lineplot.cpp
    ../../src/graphs/lixgauge.cpp
    ../../src/graphs/lixgaugegerman.cpp
    ../../src/graphs/lrroadmap.cpp
    ../../src/graphs/multi_series_lineplot.cpp
    ../../src/graphs/piechart.cpp
    ../../src/graphs/proconroadmap.cpp
    ../../src/graphs/roadmap.cpp
    ../../src/graphs/sankeydiagram.cpp
    ../../src/graphs/scalechart.cpp
    ../../src/graphs/table.cpp
    ../../src/graphs/waffle_chart.cpp
    ../../src/graphs/wcurveplot.cpp
    ../../src/graphs/win_loss_sparkline.cpp
    ../../src/graphs/wordcloud.cpp
    ../../src/import/cpp_extract_text.cpp
    ../../src/import/doc_extract_text.cpp
    ../../src/import/docx_extract_text.cpp
    ../../src/import/html_extract_text.cpp
    ../../src/import/markdown_extract_text.cpp
    ../../src/import/odt_odp_extract_text.cpp
    ../../src/import/postscript_extract_text.cpp
    ../../src/import/rtf_extract_text.cpp
    ../../src/import/xlsx_extract_text.cpp
    ../../src/ui/app.cpp
    ../../src/ui/controls/htmltablewin.cpp
    ../../src/ui/controls/htmltablewinprintout.cpp
    ../../src/ui/controls/listctrlex.cpp
    ../../src/ui/controls/listctrlexdataprovider.cpp
    ../../src/ui/controls/searchpanel.cpp
    ../../src/ui/controls/sidebar.cpp
    ../../src/ui/controls/sidebarbook.cpp
    ../../src/ui/controls/thumbnail.cpp
    ../../src/ui/dialogs/archivedlg.cpp
    ../../src/ui/dialogs/excelpreviewdlg.cpp
    ../../src/ui/dialogs/filelistdlg.cpp
    ../../src/ui/dialogs/getdirdlg.cpp
    ../../src/ui/dialogs/gridexportdlg.cpp
    ../../src/ui/dialogs/htmltablepanel.cpp
    ../../src/ui/dialogs/imageexportdlg.cpp
    ../../src/ui/dialogs/imagemergedlg.cpp
    ../../src/ui/dialogs/listctrlitemviewdlg.cpp
    ../../src/ui/dialogs/listctrlsortdlg.cpp
    ../../src/ui/dialogs/listdlg.cpp
    ../../src/ui/dialogs/opacitydlg.cpp
    ../../src/ui/dialogs/printerheaderfooterdlg.cpp
    ../../src/ui/dialogs/radioboxdlg.cpp
    ../../src/ui/dialogs/variableselectdlg.cpp
    ../../src/ui/dialogs/warningmessagesdlg.cpp
    ../../src/ui/mainframe.cpp
    ../../src/util/downloadfile.cpp
    ../../src/util/fileutil.cpp
    ../../src/util/formulaformat.cpp
    ../../src/util/hardwareinfo.cpp
    ../../src/util/i18n_string_util.cpp
    ../../src/util/idhelpers.cpp
    ../../src/util/logfile.cpp
    ../../src/util/memorymappedfile.cpp
    ../../src/util/resource_manager.cpp
    ../../src/util/screenshot.cpp
    ../../src/util/textreplace.cpp
    ../../src/util/textstream.cpp
    ../../src/util/warningmanager.cpp
    ../../src/util/xml_format.cpp
    ../../src/util/zipcatalog.cpp
    ../../src/wxSimpleJSON/src/cJSON/cJSON.c
    ../../src/wxSimpleJSON/src/wxSimpleJSON.cpp
    ../../src/wxStartPage/startpage.cpp)