/*
DO NOT EDIT.
This is generated by CMake. Re-configure the CMake file to update.
*/

// NOLINTBEGIN(cppcoreguidelines-macro-to-enum,modernize-macro-to-enum)

#define WISTERIA_VERSION_MAJOR 1
#define WISTERIA_VERSION_MINOR 2
#define WISTERIA_VERSION_PATCH 0
#define WISTERIA_VERSION_TWEAK 0
#define WISTERIA_BINARY_NAME L"Wisteria"
#define WISTERIA_APP_NAME L"Wisteria-Dataviz"
#define WISTERIA_COPYRIGHT L"Copyright (c) 2005-2026 Blake Madden"

// NOLINTEND(cppcoreguidelines-macro-to-enum,modernize-macro-to-enum)
