/*
DO NOT EDIT.
This is generated by CMake. Re-configure the CMake file to update.
*/

#define _WISTERIA_VERSION_MAJOR 1
#define _WISTERIA_VERSION_MINOR 0
#define _WISTERIA_VERSION_PATCH 7
#define _WISTERIA_VERSION_TWEAK 0
#define _WISTERIA_BINARY_NAME L"Wisteria"
#define _WISTERIA_APP_NAME L"Wisteria-Dataviz"
#define _WISTERIA_COPYRIGHT L"Copyright (c) 2005-2025 Blake Madden"
