/*
DO NOT EDIT.
This is generated by CMake. Re-configure the CMake file to update.
*/

inline constexpr int _WISTERIA_VERSION_MAJOR = 1;
inline constexpr int _WISTERIA_VERSION_MINOR = 0;
inline constexpr int _WISTERIA_VERSION_PATCH = 1;
inline constexpr int _WISTERIA_VERSION_TWEAK = 0;
inline constexpr wchar_t _WISTERIA_BINARY_NAME[] = L"Wisteria";
inline constexpr wchar_t _WISTERIA_APP_NAME[] = L"Wisteria-Dataviz";
inline constexpr wchar_t _WISTERIA_COPYRIGHT[] = L"Copyright (c) 2005-2025 Blake Madden";
