name: doxygen
on: [push, pull_request]

jobs:
  build:
    name: doxygen-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: install doxygen
        run: |
             sudo apt install doxygen

      - name: run doxygen
        run: |
             cd docs/doxygen
             doxygen Doxyfile
