name: macOS Build & Unit Tests
on: [push, pull_request]

jobs:
  build:
    name: macos-build
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Download wxwidgets
        run: |
             brew install tbb
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
 
      - name: Build
        run: |
             cmake ./
             cmake --build . -j4

      - name: Run tests
        run: |
             brew install grep
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd ${{ github.workspace }}/tests
             cmake ./
             cmake --build . -j4
             cd bin
             ./WisteriaTestRunner --reporter JUnit::out=WDV-macos-junit.xml
             cat WDV-macos-junit.xml
             errors=$(cat WDV-macos-junit.xml | ggrep -Po '(errors)="\K[^"]*')
             failures=$(cat WDV-macos-junit.xml | ggrep -Po '(failures)="\K[^"]*')
             echo "Error count is: ${errors}"
             echo "Failure count is: ${failures}"
             if [ "$errors" -gt 0 ]; then
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               exit 1
             fi

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: macOS unit tests
          path: ${{ github.workspace }}/tests/bin/*.xml
