name: Windows Build & Unit Tests

on: [push, pull_request]
env:
  project: 'Wisteria'
  testrunner: 'WisteriaTestRunner'
  outfile: 'WDV-junit.xml'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: 'recursive'

    - name: get wxwidgets
      run: |
        git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build & run tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
           cmake ./
           msbuild ${{ env.project }}.sln
           cd ..
           git clone https://github.com/catchorg/Catch2.git
           cd ${{ github.workspace }}/tests
           cmake ./
           msbuild ${{ env.testrunner }}.sln
           cd bin\Debug
           ./${{ env.testrunner }} --reporter JUnit::out=${{ env.outfile }}
           cat ${{ env.outfile }}
           $FileContent = Get-Content ${{ env.outfile }}
           $errors = (Select-String -InputObject $FileContent -Pattern 'errors="([0-9]+)"' | % { $($_.matches.groups[1]) } )
           $failures = (Select-String -InputObject $FileContent -Pattern 'failures="([0-9]+)"' | % { $($_.matches.groups[1]) } )
           if ($errors.Value -gt 0)
             {
             Write-Host "Error count is: " + $errors.Value
             exit 1
             }
           if ($failures.Value -gt 0)
             {
             Write-Host "Failure count is: " + $failures.Value
             exit 1
             }
