name: ubuntu build
on: [push]

jobs:
  build:
    name: ubuntu-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: install tools
        run: |
             sudo apt install libgtk-3-dev
             sudo apt install cmake
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
             cd wxWidgets
             mkdir buildgtk
             cd buildgtk
             ../configure --with-gtk
             make -j4
             sudo make install
             sudo ldconfig
             cd ..
             cd ..
             cd Wisteria-Dataviz
             cmake ./
             make -j4
             
      - name: build & run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd Wisteria-Dataviz/tests
             cmake ./
             make -j4
             cd bin
             ./WisteriaTestRunner --reporter JUnit::out=WDV-junit.xml
             cat WDV-junit.xml
             errors=$(cat WDV-junit.xml | grep -Po '(errors)="\K[^"]*')
             failures=$(cat WDV-junit.xml | grep -Po '(failures)="\K[^"]*')
             echo "Error count is: ${errors}"
             echo "Failure count is: ${failures}"
             if [ "$errors" -gt 0 ]; then
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               exit 1
             fi
