name: Linux Build & Unit Tests
on: [push]

jobs:
  build:
    name: ubuntu-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: install wxwidgets
        run: |
             export DISPLAY=:0.0
             sudo apt install xvfb cmake libtbb-dev libgtk-3-0 libgtk-3-dev libglib2.0-dev
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
             cd wxWidgets
             cmake . -DCMAKE_INSTALL_PREFIX=./wxlib -DwxBUILD_SHARED=OFF
             cmake --build . --target install -j4

      - name: build
        run: |
             cd ..
             cd Wisteria-Dataviz
             cmake ./
             cmake --build . -j4

      - name: run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd Wisteria-Dataviz/tests
             cmake ./
             make -j4
             cd bin
             ./WisteriaTestRunner --reporter JUnit::out=WDV-junit.xml
             cat WDV-junit.xml
             errors=$(cat WDV-junit.xml | grep -Po '(errors)="\K[^"]*')
             failures=$(cat WDV-junit.xml | grep -Po '(failures)="\K[^"]*')
             echo "Error count is: ${errors}"
             echo "Failure count is: ${failures}"
             if [ "$errors" -gt 0 ]; then
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               exit 1
             fi
