name: Linux Build & Unit Tests
on: [push, pull_request]

jobs:
  build:
    name: ubuntu-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download wxwidgets
        run: |
             export DISPLAY=:0.0
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get update && sudo apt-get install xvfb cmake libtbb-dev libgtk-3-0 libgtk-3-dev libwayland-server0 libwayland-cursor0 libwayland-client0
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules

      - name: Build
        run: |
             cmake ./
             cmake --build . -j4

      - name: Run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd Wisteria-Dataviz/tests
             cmake ./
             make -j4
             cd bin
             ./WisteriaTestRunner --reporter JUnit::out=WDV-linux-junit.xml
             cat WDV-linux-junit.xml
             errors=$(cat WDV-linux-junit.xml | grep -Po '(errors)="\K[^"]*')
             failures=$(cat WDV-linux-junit.xml | grep -Po '(failures)="\K[^"]*')
             echo "Error count is: ${errors}"
             echo "Failure count is: ${failures}"
             if [ "$errors" -gt 0 ]; then
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               exit 1
             fi

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Linux unit tests
          path: ${{ github.workspace }}/tests/bin/*.xml
